AWSTemplateFormatVersion: 2010-09-09
Resources:
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: karma-cart-ui.s3.amazonaws.com
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: 'true'
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: 'false'
          Bucket: karma-cart-ui-log.s3.amazonaws.com
          Prefix: karma-cart-ui
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
    DependsOn:
      - KarmaCartUiStaticSiteBucket
      - KarmaCartUiLogBucket
  KarmaCartUiStaticSiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: karma-cart-ui
      WebsiteConfiguration:
        IndexDocument: index.html
  KarmaCartUiLogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: karma-cart-ui-log
    DependsOn:
      - KarmaCartUiStaticSiteBucket
  KarmaCartUiStaticSiteBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref KarmaCartUiStaticSiteBucket
      PolicyDocument:
        Statement:
          - Sid: ReadAccess
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: 'arn:aws:s3:::karma-cart-ui/*'
            Principal: "*"
          - Sid: ListWriteDeleteAccess
            Action:
              - "s3:ListBucket"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Effect: "Allow"
            Resource:
              - 'arn:aws:s3:::karma-cart-ui/*'
              - 'arn:aws:s3:::karma-cart-ui'
            Principal:
                AWS: 'arn:aws:iam::156697501873:role/KarmaCartInfraCodeBuildRole'
  KarmaCartUiLogBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref KarmaCartUiLogBucket
      PolicyDocument:
        Statement:
          - Sid: ListReadWriteDeleteAccess
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Effect: "Allow"
            Resource:
              - 'arn:aws:s3:::karma-cart-ui-log/*'
              - 'arn:aws:s3:::karma-cart-ui-log'
            Principal:
                AWS: 'arn:aws:iam::765723410567:user/karmacart-admin'
